import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {

  return (
    <>
      <Head>
        <title>Next Playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Home Page</h1>
        <table className={styles.table}>
          <tbody>
            {props.array.map((item) => {
              return (
                <tr key={`${item.en}-${item.fr}`}>
                  <td>{item.en}</td>
                  <td>{item.fr}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </>
  );
}

export async function getStaticProps() {
  const data = await import("../data/vocabulary.json");
  const array = data.vocabulary;
  console.log(array);

  return {
    props: { array },
    revalidate: 20
    
  }
}
